version: "3"

services:

  backend:
    image: django
    container_name: backend
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/lib/backend/data
    expose:
      - 8001

    
volumes:
    backend:

